"""изменение таймзон в моделях

Revision ID: dfccb10b6802
Revises: 32e5b62ed4d3
Create Date: 2024-12-24 08:59:57.351273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfccb10b6802'
down_revision: Union[str, None] = '32e5b62ed4d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
