"""добавлена модель PumpCondition

Revision ID: e310ef9f298a
Revises: 85b1bfbec70b
Create Date: 2024-12-25 15:30:04.867958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e310ef9f298a'
down_revision: Union[str, None] = '85b1bfbec70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pump_condition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition', sa.Integer(), nullable=False),
    sa.Column('dttm', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pump_condition')
    # ### end Alembic commands ###
